inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - db/migrate/**
    - db/schema.rb

Rails:
  Enabled: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/initializers/dor_config.rb'

RSpec/ExampleLength:
  Max: 8
  Enabled: false

RSpec/MultipleExpectations:
  Max: 11

RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**'
