services:
  redis:
    image: redis
    ports:
      - 6379:6379
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=sekret
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
