# frozen_string_literal: true

module Migrators
  # Base migrator.
  # Depends on logic in Migrators::MigrationRunner (invokable as a script via bin/migrate-cocina) which may also
  # open/close versions, validate cocina, and/or save updated RepositoryObject records.
  #
  # The migrator subclass _must_ implement the following methods:
  #   migrate? - true if the object should be migrated
  #   migrate - migrates the object and returns the result
  # The migrator subclass _may_ override the following methods:
  #   version? - true if the object should be versioned
  #   publish? - true if the object should be published
  #   initialize(repository_object) - takes the RepositoryObject to be migrated. If possible, consider
  #     overriding this in such a way as to maintain backwards compatibility for existing migrators. E.g.,
  #     if a parameter is added, the default value could maintain the existing behavior. If breaking
  #     backwards compatibility, delete or mark deprecated/example any migrators written before the change.
  # For any repository_object where version? returns true, the migrator must implement:
  #   version_description - description for the version
  # See app/services/migrators/exemplar.rb for an example.
  class Base
    STRATEGIES = %i[cocina_update commit commit_with_version commit_with_publish].freeze

    # @param model_hash [Hash] has generated by RepositoryObjectVersion.to_h
    # @param valid [Boolean] whether the model_hash is valid according to the current cocina models
    # @param opened_version [Boolean] whether this is the open version
    # @param last_closed_version [Boolean] whether this is the last closed version
    # @param head_version [Boolean] whether this is the head version
    def initialize(model_hash:, valid:, opened_version:, last_closed_version:, head_version:)
      @model_hash = model_hash
      @opened_version = opened_version
      @last_closed_version = last_closed_version
      @head_version = head_version
      @valid = valid

      raise ArgumentError, 'Invalid migration strategy' unless STRATEGIES.include?(self.class.migration_strategy)
    end

    # A migrator must implement a migrate method that migrates (mutates) the model hash.
    # @return [Hash] the migrated model hash
    def migrate
      raise NotImplementedError
    end

    # @return [String] the migration strategy to use for this migrator. See STRATEGIES for valid strategies.
    def self.migration_strategy
      :commit
    end

    # @return [String] version description for the migrated version (if versioning)
    def self.version_description
      raise NotImplementedError
    end

    # @return [Boolean] true if changed migrated objects should be published, false otherwise
    def self.publish?
      migration_strategy == :commit_with_publish
    end

    # @return [Boolean] true if a cocina model is allowed to be migrated from valid to invalid.
    def self.allow_invalid?
      false
    end

    # @return [Boolean] true if migrated objects should be versioned, false otherwise
    def self.version?
      %i[commit_with_version cocina_update].include?(migration_strategy)
    end

    # @return [Boolean] true if UpdateObjectService should be used to persist changes
    def self.cocina_update?
      migration_strategy == :cocina_update
    end

    private

    attr_reader :model_hash

    def head_version?
      @head_version
    end

    def opened_version?
      @opened_version
    end

    def last_closed_version?
      @last_closed_version
    end

    def valid?
      @valid
    end
  end
end
