# frozen_string_literal: true

module Migrators
  # Migrator to refresh metadata from a dump of MARC records from Folio.
  # This requires that the dump be in place and that the database be built from the dump before running the migration.
  # The dump must be a set of gzipped MARC files (*.mrc.gz) placed in Settings.catalog.folio.refresh.dump_path.
  # The database can be generated by running Catalog::MarcDump.new.build_db! from the Rails console.
  # When migration is complete, make sure to delete the dump and database.
  class FolioRefresh < Base
    def migrate
      return model_hash unless refreshable_hrid

      marc_record = Catalog::MarcDump.new.find(refreshable_hrid)
      description_props = Cocina::FromMarc::Description
                          .props(marc: marc_record, druid: model_hash['externalIdentifier'])
      model_hash['description'] = description_props
      model_hash
    end

    def self.migration_strategy
      :cocina_update
    end

    # @return [String] version description for the migrated version (if versioning)
    def self.version_description
      'Refresh description from Folio.'
    end

    private

    def refreshable_hrid
      @refreshable_hrid ||= begin
        catalog_link = Array(model_hash.dig('identification', 'catalogLinks')).find do |link|
          link['catalog'] == 'folio' && link['refresh']
        end
        catalog_link['catalogRecordId'] if catalog_link
      end
    end
  end
end
