# frozen_string_literal: true

# This was generated by graphql gem.
module Types
  class MutationType < Types::BaseObject
    # Examples created by the generator
    # field :test_field, String, null: false,
    #                            description: 'An example field added by the generator'
    # def test_field
    #   'Hello World'
    # end
  end
end
