default: &default
  adapter: postgresql
  encoding: unicode
  database: "<%= ENV.fetch('DATABASE_NAME', 'dor_services') %>"
  username: "<%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>"
  password: "<%= ENV.fetch('DATABASE_PASSWORD', 'sekret') %>"
  host: "<%= ENV.fetch('DATABASE_HOSTNAME', 'localhost') %>"
  port: "<%= ENV.fetch('DATABASE_PORT', 5432) %>"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  pool: 10 # same as sidekiq concurrency
