---
request:
  filter_keys:
    - 'HTTP_AUTHORIZATION'
    - 'HTTP_X_AUTH'
exceptions:
  ignore:
    - 'ReindexJob::DeadLockError'
stage:
  exceptions:
    ignore:
      - 'ReindexJob::DeadLockError'
      - 'PreservationIngestService::VersionMismatchError'      
insights:
  enabled: false
